// Code generated by MockGen. DO NOT EDIT.
// Source: internal/model/exchange_rates/model.go

// Package mock_exchange_rates is a generated GoMock package.
package mock_exchange_rates

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GetExchangeRateToRUB mocks base method.
func (m *MockClient) GetExchangeRateToRUB() map[string]float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExchangeRateToRUB")
	ret0, _ := ret[0].(map[string]float64)
	return ret0
}

// GetExchangeRateToRUB indicates an expected call of GetExchangeRateToRUB.
func (mr *MockClientMockRecorder) GetExchangeRateToRUB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExchangeRateToRUB", reflect.TypeOf((*MockClient)(nil).GetExchangeRateToRUB))
}

// GetExchangeRateToRUBFromDate mocks base method.
func (m_2 *MockClient) GetExchangeRateToRUBFromDate(ctx context.Context, y, m, d int) (map[string]float64, error) {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "GetExchangeRateToRUBFromDate", ctx, y, m, d)
	ret0, _ := ret[0].(map[string]float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExchangeRateToRUBFromDate indicates an expected call of GetExchangeRateToRUBFromDate.
func (mr *MockClientMockRecorder) GetExchangeRateToRUBFromDate(ctx, y, m, d interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExchangeRateToRUBFromDate", reflect.TypeOf((*MockClient)(nil).GetExchangeRateToRUBFromDate), ctx, y, m, d)
}
