// Code generated by MockGen. DO NOT EDIT.
// Source: internal/model/purchases/model.go

// Package mock_purchases is a generated GoMock package.
package mock_purchases

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	purchases "gitlab.ozon.dev/apetrichuk/financial-tg-bot/internal/model/purchases"
)

// MockRepo is a mock of Repo interface.
type MockRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRepoMockRecorder
}

// MockRepoMockRecorder is the mock recorder for MockRepo.
type MockRepoMockRecorder struct {
	mock *MockRepo
}

// NewMockRepo creates a new mock instance.
func NewMockRepo(ctrl *gomock.Controller) *MockRepo {
	mock := &MockRepo{ctrl: ctrl}
	mock.recorder = &MockRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepo) EXPECT() *MockRepoMockRecorder {
	return m.recorder
}

// AddPurchase mocks base method.
func (m *MockRepo) AddPurchase(req purchases.AddPurchaseReq) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPurchase", req)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddPurchase indicates an expected call of AddPurchase.
func (mr *MockRepoMockRecorder) AddPurchase(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPurchase", reflect.TypeOf((*MockRepo)(nil).AddPurchase), req)
}

// CategoryExist mocks base method.
func (m *MockRepo) CategoryExist(req purchases.CategoryExistReq) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CategoryExist", req)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0
}

// CategoryExist indicates an expected call of CategoryExist.
func (mr *MockRepoMockRecorder) CategoryExist(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CategoryExist", reflect.TypeOf((*MockRepo)(nil).CategoryExist), req)
}
